"""
Red Team case-authoring script for the video_kyc_impersonation family
(docs/TECHNICAL_SPEC.md Section 4c) -- the video-KYC counterpart to
generate_voice_attacks.py, but structurally different in one important way:
the actual media (reference photos and bonafide videos) is NOT generated by
this script. The user generates that media by hand via Kling and ChatGPT
image generation. This script's job is case AUTHORING: discover whichever
identities already have both a reference photo and a bonafide video on
disk, and write the case JSONs that eval_video_kyc.py will later score --
INCREMENTALLY, safely re-run any number of times as more media lands.

2026-08-31 design history, most recent revision first:

  Media generation is happening in real time while this script is being
  iterated on, so it was rewritten TWICE in one session in response to real
  facts on disk, not guessed in advance -- consistent with this project's
  evidence-gate discipline (react to what's actually there, don't assume):

  (a) Originally keyed identities to synthetic_customers.py's CUST-######
      roster (rng.sample of 10, split 7 train / 3 held_out) and to a
      dedicated Kling motion_control face-swap tool for the held_out tier.
      motion_control was dropped because it's a face-swap/reenactment
      capability that Kling's own policy restricts even for synthetic
      identities -- see video_kyc_detector.py's docstring.

  (b) The CUST-###### roster coupling was ALSO dropped once real files
      landed on disk: the user is naming identities by generated first
      name (Khushi.png, Naresh.png, Sam.mp4, ...), not by the tabular
      customer roster's ids -- and nothing else in the codebase reads
      video_ref/photo_ref off that roster yet (both are still hardcoded
      None there), so there is no real coupling to preserve. Video-KYC now
      has its own flat, self-contained identity namespace: whatever stem a
      photo+video pair share (case-insensitively) under video_kyc_reference/
      and video_kyc_bonafide/ IS a video-KYC identity, full stop. If this
      signal is ever folded into cross-modal fusion alongside voice/
      document (Section 4b's "identity" category), a mapping back to the
      main customer roster can be added then -- not needed for pass 1.

  This also means the earlier plan for a dedicated, deliberately-generated
  "lookalike impostor" per held_out victim (a second photo+video pair
  visually resembling the victim, named IMPOSTOR-<victim>) is DOWNGRADED
  from a hard requirement to an optional refinement: this script no longer
  requires that naming convention to make progress, because blocking all
  case authoring on a naming convention the user isn't using in practice
  would be exactly the kind of avoidable failure the user just asked to
  eliminate. If dedicated IMPOSTOR-<name>.{png,mp4} files ARE found (case-
  insensitive stem prefix match), they're used preferentially as that
  victim's held_out impostor -- deliberately harder, real visual-similarity
  intent preserved. Where none exists yet, held_out falls back to the same
  arbitrary-pairing mechanism as train; the honest label for that fallback
  is "novel identity combination not seen in train" (Section 4a's general
  train/held_out convention), not "engineered harder difficulty" -- and
  each held_out case's mutation_params record which of the two actually
  happened, so this is never silently overstated later.

Ground-truth-by-construction (parallel to document_consistency's pattern):
bonafide = a video generated FROM the identity's own registered reference
photo, submitted under its own claimed name. Attack = a DIFFERENT
identity's own unmodified video, submitted under a false claim. No file in
this project ever generates or requests a face-swap/reenactment output --
every attack video is a genuine (synthetic) person's own real footage,
mislabeled. Ground truth lives in this script's case JSON (customer_id =
claimed identity, impostor_customer_id = who the video actually shows,
ground-truth bookkeeping ONLY, never passed to video_kyc_detector.py --
Principle 13).

Idempotent and incremental (the actual point of this revision): before
writing anything, this script reads every existing case JSON already under
OUT_DIR and skips any (customer_id, tier) combination already covered --
re-running after generating 2 more videos only authors the NEW cases those
2 unlock, it never duplicates or reshuffles what's already there. Never
raises for "not everything is ready yet" -- prints exactly what's still
missing and exits 0, so it can be wired into a "run this after every batch
of media lands" habit without ever being a red X.

Expected folder layout:
    data/generated/video_kyc_reference/<name>.{png,jpg,jpeg}            (case-insensitive)
    data/generated/video_kyc_reference/IMPOSTOR-<name>.{png,jpg,jpeg}   (optional, preferred for held_out)
    data/generated/video_kyc_bonafide/<name>.mp4
    data/generated/video_kyc_bonafide/IMPOSTOR-<name>.mp4               (optional, preferred for held_out)
    data/generated/video_kyc_attacks/train/<case_id>.json
    data/generated/video_kyc_attacks/held_out/<case_id>.json

Usage:
    python backend/generate/generate_video_kyc_attacks.py
"""

import hashlib
import json
import sys
import uuid
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_DIR))

REPO_ROOT = BACKEND_DIR.parent
REFERENCE_DIR = REPO_ROOT / "data" / "generated" / "video_kyc_reference"
BONAFIDE_DIR = REPO_ROOT / "data" / "generated" / "video_kyc_bonafide"
OUT_DIR = REPO_ROOT / "data" / "generated" / "video_kyc_attacks"

FAMILY = "video_kyc_impersonation"
PHOTO_EXTS = (".png", ".jpg", ".jpeg")
IMPOSTOR_PREFIX = "IMPOSTOR-"
HELD_OUT_FRACTION_NUM = 3   # ~30% of identities go to held_out -- deterministic per-name hash, see _split_bucket()
HELD_OUT_FRACTION_DEN = 10


def _stem_index(directory: Path, exts: tuple) -> dict:
    """Case-insensitive {lowercased stem: Path} for every matching file in
    directory. Built once per run -- device_bash's mounted filesystem
    behavior around case sensitivity isn't something to assume either way,
    so matching is done explicitly in Python instead of relying on the
    filesystem to fold case for us."""
    index = {}
    if not directory.exists():
        return index
    for p in directory.iterdir():
        if p.is_file() and p.suffix.lower() in exts:
            index[p.stem.lower()] = p
    return index


def _split_bucket(name: str) -> str:
    """Deterministic, stable train/held_out assignment per identity name --
    does NOT depend on how many other identities exist or the order they
    were discovered in, so it never reshuffles an already-authored
    identity's split as more media lands. ~30% held_out."""
    digest = hashlib.sha256(name.lower().encode("utf-8")).hexdigest()
    bucket = int(digest[:8], 16) % HELD_OUT_FRACTION_DEN
    return "held_out" if bucket < HELD_OUT_FRACTION_NUM else "train"


def _discover_ready_identities() -> list:
    """Returns sorted list of identity names (photo-file stems, original
    case preserved from the photo file) that have BOTH a reference photo
    and a bonafide video on disk. Excludes IMPOSTOR-* stems -- those are
    impostor material, never a claimable identity in their own right."""
    photos = _stem_index(REFERENCE_DIR, PHOTO_EXTS)
    videos = _stem_index(BONAFIDE_DIR, (".mp4",))
    names = []
    for stem_lower, photo_path in photos.items():
        if stem_lower.startswith(IMPOSTOR_PREFIX.lower()):
            continue
        if stem_lower in videos:
            names.append(photo_path.stem)  # original-case name, for readability in case JSON
    return sorted(names, key=str.lower)


def _dedicated_impostor(name: str) -> "tuple[Path, Path] | None":
    """Returns (photo_path, video_path) for IMPOSTOR-<name> if BOTH exist,
    else None."""
    photos = _stem_index(REFERENCE_DIR, PHOTO_EXTS)
    videos = _stem_index(BONAFIDE_DIR, (".mp4",))
    key = (IMPOSTOR_PREFIX + name).lower()
    if key in photos and key in videos:
        return photos[key], videos[key]
    return None


def _existing_case_keys() -> set:
    """(customer_id, tier) pairs already authored under OUT_DIR -- the
    idempotency guard. Reads every existing case JSON once per run; cheap
    at this dataset's scale (tens of cases, not thousands)."""
    keys = set()
    for path in OUT_DIR.glob("*/*.json"):
        try:
            case = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        tier = (case.get("mutation_params") or {}).get("tier")
        keys.add((case.get("customer_id"), tier))
    return keys


def _rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT)) if path.is_relative_to(REPO_ROOT) else str(path)


def _write_case(split_portion: str, customer_id: str, impostor_customer_id: "str | None",
                 video_path: Path, reference_photo_path: Path, is_fraud: bool,
                 tier: str, extra_params: dict) -> str:
    case_id = f"{FAMILY}_{uuid.uuid4().hex[:12]}"
    mutation_params = {"tier": tier, **extra_params}
    case = {
        "case_id": case_id,
        "attack_family": FAMILY,
        "split_portion": split_portion,
        "mutation_params": mutation_params,
        "resolved_levels": mutation_params,
        "signals_expected": ["identity"],
        "customer_id": customer_id,
        "impostor_customer_id": impostor_customer_id,  # ground truth ONLY -- never passed to the detector
        "video_path": _rel(video_path),
        "reference_photo_path": _rel(reference_photo_path),
        "is_fraud": is_fraud,
    }
    (OUT_DIR / split_portion).mkdir(parents=True, exist_ok=True)
    (OUT_DIR / split_portion / f"{case_id}.json").write_text(json.dumps(case, indent=2))
    return case_id


def main() -> None:
    ready = _discover_ready_identities()
    print(f"Discovered {len(ready)} identities with both a reference photo and a bonafide video: "
          f"{', '.join(ready) if ready else '(none yet)'}")

    photos = _stem_index(REFERENCE_DIR, PHOTO_EXTS)
    videos = _stem_index(BONAFIDE_DIR, (".mp4",))
    photo_only = sorted((photos.keys() - videos.keys()) - {k for k in photos if k.startswith(IMPOSTOR_PREFIX.lower())},
                        key=str.lower)
    video_only = sorted((videos.keys() - photos.keys()) - {k for k in videos if k.startswith(IMPOSTOR_PREFIX.lower())},
                        key=str.lower)
    if photo_only:
        print(f"  waiting on a bonafide video for: {', '.join(photo_only)}")
    if video_only:
        print(f"  waiting on a reference photo for: {', '.join(video_only)}")

    if len(ready) < 2:
        print("\nFewer than 2 ready identities -- need at least 2 to author any attack case "
              "(an attack needs a distinct impostor identity's video). Nothing written this run; "
              "re-run once more media lands. Exiting cleanly (not an error).")
        return

    existing = _existing_case_keys()
    written = {"bonafide": 0, "attack": 0}
    skipped_existing = 0

    # 1. Bonafide case per ready identity, under its own claimed name.
    buckets = {name: _split_bucket(name) for name in ready}
    for name in ready:
        key = (name, "bonafide_self")
        if key in existing:
            skipped_existing += 1
            continue
        _write_case(
            buckets[name], customer_id=name, impostor_customer_id=None,
            video_path=videos[name.lower()], reference_photo_path=photos[name.lower()],
            is_fraud=False, tier="bonafide_self", extra_params={},
        )
        written["bonafide"] += 1

    # 2. Attack case per ready identity, claiming to be that identity but showing
    # someone else's own unmodified video. train: arbitrary round-robin pairing
    # among all ready identities. held_out: prefers a dedicated IMPOSTOR-<name>
    # pair if the user has generated one (real, intended visual-similarity
    # difficulty); falls back to the same arbitrary pairing as train otherwise
    # (honestly labeled as a novel-combination case, not an engineered-harder one).
    for i, victim in enumerate(ready):
        split_portion = buckets[victim]
        dedicated = _dedicated_impostor(victim) if split_portion == "held_out" else None

        if dedicated is not None:
            impostor_photo, impostor_video = dedicated
            impostor_id = f"{IMPOSTOR_PREFIX}{victim}"
            tier = "lookalike_impostor"
            extra = {"impostor_video_reused_unmodified": True, "impostor_pairing": "deliberate_lookalike"}
        else:
            impostor = ready[(i + 1) % len(ready)]
            if impostor == victim:  # only possible when len(ready) == 1, already guarded above
                continue
            impostor_video = videos[impostor.lower()]
            impostor_id = impostor
            tier = "unaltered_impostor" if split_portion == "train" else "unaltered_impostor_held_out"
            extra = {
                "impostor_video_reused_unmodified": True,
                "impostor_pairing": "arbitrary_round_robin",
                **({"note": "no dedicated lookalike impostor generated yet for this held_out identity -- "
                            "novel-combination case, not an engineered-harder one"} if split_portion == "held_out" else {}),
            }

        key = (victim, tier)
        if key in existing:
            skipped_existing += 1
            continue
        _write_case(
            split_portion, customer_id=victim, impostor_customer_id=impostor_id,
            video_path=impostor_video, reference_photo_path=photos[victim.lower()],
            is_fraud=True, tier=tier, extra_params=extra,
        )
        written["attack"] += 1

    print(f"\nWrote {written['bonafide']} new bonafide case(s), {written['attack']} new attack case(s) "
          f"under {OUT_DIR} ({skipped_existing} already existed, skipped -- idempotent re-run).")
    n_held_out_ready = sum(1 for n in ready if buckets[n] == "held_out")
    n_dedicated = sum(1 for n in ready if buckets[n] == "held_out" and _dedicated_impostor(n) is not None)
    print(f"Split so far: {len(ready) - n_held_out_ready} train / {n_held_out_ready} held_out "
          f"({n_dedicated}/{n_held_out_ready} held_out identities have a dedicated lookalike impostor).")
    print("Safe to re-run this script after every new photo/video lands.")


if __name__ == "__main__":
    main()
